node {
  name = "emqx@emqx"
  cookie = "torquesecretcookie"
  data_dir = "/opt/emqx/data"
}

listeners.wss.default {
  enable = false
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  ssl_options {
    cacertfile = "/opt/emqx/etc/certs/ca.crt"
    certfile = "/opt/emqx/etc/certs/server.crt"
    keyfile = "/opt/emqx/etc/certs/server.key"
    verify = verify_peer
    fail_if_no_peer_cert = true
  }
}

authentication = [
  {
    mechanism = password_based
    backend = http
    method = post
    url = "http://host.docker.internal:8081/mqtt/auth"
    body {
      clientid = "${clientid}"
      cn = "${cert_common_name}"
    }
    headers {
      "Content-Type" = "application/json"
      "X-Guard-Secret" = "changeme"
    }
    request_timeout = 5s
  }
]

authorization {
  no_match = deny
  deny_action = disconnect
  cache { enable = false }
  sources = [
    {
      type = http
      enable = true
      method = post
      url = "http://host.docker.internal:8081/mqtt/acl"
      body {
        clientid = "${clientid}"
        cn = "${cert_common_name}"
        topic = "${topic}"
        action = "${action}"
      }
      headers {
        "Content-Type" = "application/json"
        "X-Guard-Secret" = "changeme"
      }
      request_timeout = 5s
    }
  ]
}
